# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/jay/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="jay"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)
plugins=(git npm osx sublime history-substring-search django cloudapp dircycle dirhistory git-extras pip tmux tmuxinator vagrant web-search)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=/usr/local/share/python/:/usr/local/share/npm/bin/:/usr/local:/usr/local/bin:/Users/jay/Scripts:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/share/npm/bin/:/Users/jay/Scripts:$PATH
export NODE_PATH=/usr/local/lib/node_modules
export EDITOR=vim
# export EDITOR="subl -w"
# export EDITOR="atom -w"
export ATOM_REPOS_HOME=/Users/jay/Projects/Atom/
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export ZSH_TMUX_AUTOCONNECT=false

source ~/dotfiles/client/zsh/shellvars.zsh
source ~/dotfiles/venuebook-vagrant/bin/tmuxinator.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  chruby 2.3.3
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  chruby 2.3.3
fi

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_PAPER=en_US.UTF-8
export LC_NAME=en_US.UTF-8
export LC_ADDRESS=en_US.UTF-8
export LC_TELEPHONE=en_US.UTF-8
export LC_MEASUREMENT=en_US.UTF-8
export LC_IDENTIFICATION=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias rb="bundle exec ruby"
alias fuck='$(thefuck $(fc -ln -1))'
alias build="gulp build:js -p -f"
alias watchify="gulp build:js -w -f"
alias bundle="gulp build:js -f"
alias vb=$vb
alias vbjs="cd ~/Projects/venuebook/venuebook.com/instevent/app/main/js/app && cd "
alias prune-local-branches="git branch --list --no-color | sed 's/\*/ /g' | xargs -n1 -p git branch -D"
alias prune-origin-branches="git branch --list --no-color -r | grep origin/ | tail +2 | sed 's/\// :/g' | xargs -n2 -p git push"
alias prune-root-branches="git branch --list --no-color -r | grep root/ | tail +2 | sed 's/\// :/g' | xargs -n2 -p git push"
alias prune-branches="prune-local-branches && prune-origin-branches && prune-root-branches"

searchjs() {
  ack $* -- ~/Projects/venuebook/venuebook.com/instevent/app/main/js
}

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

source ~/.fonts/devicons-regular.sh
source ~/.fonts/fontawesome-regular.sh
source ~/.fonts/octicons-regular.sh
source ~/.fonts/pomicons-regular.sh

powerline-daemon -q
. /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=/Users/jay/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
